import sys

from PyQt5.QtCore import QPoint

from PyQt5.QtGui import QPixmap, QImage, QTransform, QColor
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow, QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets


# run again.  Do not edit this file unless you know what you are doing.
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 451)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.channelButtons = QtWidgets.QButtonGroup(MainWindow)
        self.channelButtons.setObjectName("channelButtons")
        self.channelButtons.addButton(self.pushButton)
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.channelButtons.addButton(self.pushButton_2)
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.channelButtons.addButton(self.pushButton_3)
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.channelButtons.addButton(self.pushButton_4)
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setMinimumSize(QtCore.QSize(250, 250))
        self.image.setMaximumSize(QtCore.QSize(260, 260))
        self.image.setObjectName("image")
        self.horizontalLayout.addWidget(self.image)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.rotateButtons = QtWidgets.QButtonGroup(MainWindow)
        self.rotateButtons.setObjectName("rotateButtons")
        self.rotateButtons.addButton(self.pushButton_5)
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.rotateButtons.addButton(self.pushButton_6)
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PIL 2.0"))
        self.pushButton.setText(_translate("MainWindow", "R"))
        self.pushButton_2.setText(_translate("MainWindow", "G"))
        self.pushButton_3.setText(_translate("MainWindow", "B"))
        self.pushButton_4.setText(_translate("MainWindow", "ALL"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("MainWindow", "Против часовой стрелки"))
        self.pushButton_6.setText(_translate("MainWindow", "По часовой стрелке"))


SCREEN_SIZE = [400, 400]


class MyPillow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.initUI()

    def initUI(self):
        self.setGeometry(400, 400, *SCREEN_SIZE)
        self.setWindowTitle('Отображение картинки')
        self.fname = QFileDialog.getOpenFileName(self, 'Выбрать картинку', '')[0]
        self.orig_image = QImage(self.fname)
        self.curr_image = self.orig_image.copy()

        self.pixmap = QPixmap.fromImage(self.curr_image)
        self.image.setPixmap(self.pixmap)
        for button in self.channelButtons.buttons():
            button.clicked.connect(self.set_channel)
        for button in self.rotateButtons.buttons():
            button.clicked.connect(self.rotate)
        self.degree = 0

    def set_channel(self):
        self.curr_image = self.orig_image.copy()
        x, y = self.curr_image.size().width(), self.curr_image.size().height()
        for i in range(x):
            for j in range(y):
                r, g, b, _ = self.curr_image.pixelColor(i, j).getRgb()
                if self.sender() is self.pushButton:
                    self.curr_image.setPixelColor(QPoint(i, j), QColor(r, 0, 0))
                if self.sender() is self.pushButton_2:
                    self.curr_image.setPixelColor(QPoint(i, j), QColor(0, g, 0))
                if self.sender() is self.pushButton_3:
                    self.curr_image.setPixelColor(QPoint(i, j), QColor(0, 0, b))
                if self.sender() is self.pushButton_4:
                    self.curr_image.setPixelColor(QPoint(i, j), QColor(r, g, b))
        t = QTransform().rotate(self.degree)
        self.curr_image = self.curr_image.transformed(t)
        self.pixmap = QPixmap.fromImage(self.curr_image)
        self.image.setPixmap(self.pixmap)

    def rotate(self):
        if self.sender() is self.pushButton_6:
            self.degree += 90
            degree = 90
        if self.sender() is self.pushButton_5:
            self.degree -= 90
            degree = -90
        self.degree %= 360
        t = QTransform().rotate(degree)
        self.curr_image = self.curr_image.transformed(t)
        self.pixmap = QPixmap.fromImage(self.curr_image)
        self.image.setPixmap(self.pixmap)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyPillow()
    ex.show()
    sys.exit(app.exec())
